/* Autogenerated by hxtools bin2c */
#ifndef PNGA_H
#define PNGA_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_A_png[49526];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* PNGA_H */
