/* Autogenerated by hxtools bin2c */
#ifndef PNGB_H
#define PNGB_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_B_png[42501];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* PNGB_H */
